- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
- scm/etc/Cheyenne_setup_pgi.csh
- scm/etc/Cheyenne_setup_pgi.sh
Update v3.0 release branch with new cheyenne modules following cheyenne o/s upgrade.
The multi-suite test runs successfully for Intel and Gnu on cheyenne. PGI currently fails to compile.
> Update cheyenne modules

- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
tested using Intel and GNU on Cheyenne
> updated NCEPLIBS_DIR in Cheyenne setup scripts for GNU and Intel

- scm/etc/Hera_setup_intel.csh
- scm/etc/Hera_setup_intel.sh
Add support for Hera machine (Intel only for now) by adding machine setup scripts. (Tested successfully on Hera)
> Hera support

- ccpp/suites/suite_SCM_GFS_2017_myj.xml
- ccpp/suites/suite_SCM_GFS_v15.xml
- ccpp/suites/suite_SCM_GFS_v15_noahmp.xml
- ccpp/suites/suite_SCM_GFS_v15_prescribed_surface.xml
- ccpp/suites/suite_SCM_GFS_v15plus.xml
- ccpp/suites/suite_SCM_GFS_v15plus_prescribed_surface.xml
- ccpp/suites/suite_SCM_GSD_v0.xml
- ccpp/suites/suite_SCM_GSD_v0_prescribed_surface.xml
- ccpp/suites/suite_SCM_csawmg.xml
- ccpp/suites/suite_SCM_csawmg_prescribed_surface.xml
- scm/src/default_namelists.py
- Add changes to SDFs to reflect GWD scheme reorganization
- similar to https://github.com/NCAR/fv3atm/pull/1
> Reinstate gwd interstitial reorg

- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
- scm/etc/Hera_setup_intel.csh
- scm/etc/Hera_setup_intel.sh
- updated submodule pointers for latest release/public-v4 branches of ccpp-physics and ccpp-framework
- updated machine setup scripts to match those in release branch of ufs-weather-model
- include change for using anaconda python on Hera (that already exists in master)
This update has been tested successfully on Hera/intel (prod/debug), Cheyenne/intel (prod/debug), Cheyenne/gnu (prod/debug), Mac clang/gnu9.1
> Update for v4.1 CCPP release

- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
- scm/etc/Hera_setup_intel.csh
- scm/etc/Hera_setup_intel.sh
- scm/etc/scripts/forcing_file_common.py
- scm/etc/scripts/gmtb_scm_analysis.py
- scm/etc/scripts/gmtb_scm_plotting_routines.py
- scm/src/multi_run_gmtb_scm.py
- scm/src/run_gmtb_scm.py
1. add Dom's python 3 compatibility changes for run scripts from master branch
2. add python 3 compatibility for plot* scripts
3. change to python 3 for compute environments on Hera and Cheyenne
*edited
> python3 compatibility for release branch

- contrib/get_thompson_tables.sh
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- update GFS_typedefs.[F90,meta] to work with latest ccpp-physics/framework main; update thompson table retrieval script to grab v2 files now required by Thompson scheme
> Update to latest ccpp-physics/framework

- contrib/get_mg_inccn_data.sh
- contrib/get_thompson_tables.sh
- docker/Dockerfile
- Add missing environment variable to Dockerfile
- Update all static data files to .gz for consistency and smaller file size
> A few final v6 changes

- .github/workflows/ci_run_scm_rts.yml
This adds an gitHub workflow event-trigger, workflow_dispatch, allowing the workflow to be run through the GitHub api.
> Added workflow_dispath to CI event triggers.

- scm/etc/Hera_setup_intel.sh
Looks like it was an accidental paste
> Typo in Hera_setup_intel.sh

- .gitmodules
- scm/src/CCPP_typedefs.meta
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- changes to typedefs to work with https://github.com/NCAR/ccpp-physics/pull/1009. 
- analogous to https://github.com/NCAR/fv3atm/pull/91
> UFS-dev PR#49

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- changes to typedefs to work with ufs/dev PR#57: https://github.com/NCAR/ccpp-physics/pull/1010
> UFS-dev PR#57

- scm/etc/case_config/AYOTTE_00SC.nml
- scm/etc/case_config/BOMEX_REF.nml
- scm/etc/case_config/DYNAMO_NSA3a.nml
- scm/etc/case_config/DYNAMO_NSA3a_D1.nml
- scm/etc/case_config/GABLS1_REF.nml
- scm/etc/case_config/IHOP_REF.nml
- scm/etc/case_config/MPACE_REF.nml
- scm/etc/case_config/RICO_MESONH.nml
- scm/etc/case_config/SANDU_FAST.nml
- scm/etc/case_config/SANDU_REF.nml
- scm/etc/case_config/SANDU_SLOW.nml
- scm/etc/case_config/SCMS_REF.nml
- scm/src/scm_input.F90
Addresses comment in https://github.com/NCAR/ccpp-scm/discussions/383
> Remove reference_profile_dir from case_config namelists

- .gitmodules
- scm/src/CCPP_typedefs.F90
Changes corresponding to https://github.com/NCAR/fv3atm/pull/102 and https://github.com/NCAR/ccpp-physics/pull/1032
> UFS-dev PR#88

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to work with https://github.com/NCAR/fv3atm/pull/104 and https://github.com/NCAR/ccpp-physics/pull/1034
Contains changes from #404 until merged.
> UFS-dev PR#92

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NCAR/fv3atm/pull/109
> UFS/dev PR#118

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NCAR/fv3atm/pull/115
> UFS-dev PR#120

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to work with https://github.com/NCAR/ccpp-physics/pull/1060
> UFS-dev PR#155

- scm/src/CCPP_typedefs.F90
- scm/src/CCPP_typedefs.meta
Changes analogous to https://github.com/NCAR/fv3atm/pull/127
> UFS-dev PR#181

- environment-scm_analysis.yml
- environment-tutorial.yml
Add yaml script for python environment used in online tutorial.
@hertneky This should now work w/ https://dtcenter.org/ccpp-scm-online-tutorial/exercise-1-run-scm-examine-results
> Add yaml script for python environment used in online tutorial.

- environment-scm_analysis.yml
The yaml file to create the SCM tutorial environment for the scm_analysis script required a couple extra packages.
> additions to tutorial yaml

- .gitmodules
Updates ccpp/physics submodule pointer only.
No RT baseline changes over and above previous PR (#527 ).
> UFS/dev PR#219

- scm/src/scm_output.F90
Fix a typo in units for surface skin temperature found by @egrell
> fix tsfc units in output

- CODEOWNERS
> add Tracy and Soren as CODEOWNERS

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This PR catches the NCAR:main branch up with changes from the ufs-community:ufs/dev branch. 
- ufs-community/ccpp-physics#252
- NOAA-EMC/fv3atm#926
- NCAR/ccpp-physics#1114
> UFS-dev PR#252 Tenth reconciliation PR from production/RRFS.v1

- .gitmodules
- Updating hash of submodule ccpp-physics, didn't undo testing changes in #581 before merge
> Updating to ccpp-physics PR#1133 hash

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- ufs-community/ccpp-physics#248
- NOAA-EMC/fv3atm#917
- NCAR/ccpp-physics#1139
---
REGRESSION TEST CHANGES: Enter NONE if not applicable. Otherwise, expected results changes, input data changes, changes to the software, etc.
NONE
> Ufs dev 248
