- scm/src/GFS_typedefs.F90
The Morrison-Gettelman arrays in the Interstitial data type were conditionally allocated in GFS_physics_driver.F90, but not in GFS_typedefs.F90 with the CCPP. This will reduce the memory footprint when not running with the MG scheme.
> conditionally allocate MG arrays

- scm/src/CMakeLists.txt
This PR
- Updates the submodule pointer for ccpp/physics to fix the broken dtc/develop branch (following PR https://github.com/NCAR/gmtb-scm/pull/141 which didn't update the submodule pointer).
- Runs `ccpp_prebuild.py` as part of the cmake step for both the dynamic and static CCPP. For the static build, a list of all suites is generated from the suites directory and compiled into the executable.
This code was tested successfully on
- hera+intel in "Release" mode
- cheyenne+gnu in "Release" mode
- macos+clang/gfortran in "Release" mode (build/compile only)
for both dynamic and static CCPP.
**Warning** The SCM code is currently broken in "Debug" mode:
- For the Intel compiler, the compilation step fails because of mismatching arguments in `ugwp_driver_v0.F` (see known issue …
> dtc/develop: run CCPP prebuild step from cmake

- scm/src/CMakeLists.txt
-replace string append operation in CMakeLists.txt with different syntax to work with older versions of cmake
-from what I can tell, STRING(APPEND) first appeared in version 3.4.
followup to PR #142 
tested to work on Hera/Intel with default cmake and Mac OS
> fix CMakeLists.txt to work with older default version on Hera

- scm/src/gmtb_scm_type_defs.f90
initialize Sfcprop%tsfco and Sfcprop%tisfc since they no longer get initialized in physics after fractional land surface changes from a few months ago; this fixes the runtime error in Debug mode
> fix debug mode runtime error

- .gitmodules
- update submodule pointer for ccpp-physics following the merge of https://github.com/NCAR/ccpp-physics/pull/354.
- update .gitmodules to point to the correct branches dtc/develop for the submodules (so that `git submodule update --remote` works as intended)
No testing required, will merge immediately.
> dtc/develop: update submodule pointer ccpp physics 2019/11/25

- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/gmtb_scm_physical_constants.f90
- scm/src/gmtb_scm_physical_constants.meta
- scm/src/gmtb_scm_type_defs.f90
- added new files to CCPP prebuild configuration
- mirrored changes to GFS_typedefs.[F90,meta] from https://github.com/NCAR/fv3atm/pull/2 and https://github.com/NCAR/fv3atm/pull/10
Note: No SDF or namelist for F-A added in this PR (this PR is for fixing the build only!)
> update for adding Ferrier-Aligo MP

- ccpp/config/ccpp_prebuild_config.py
- ccpp/suites/suite_SCM_GFS_v15_noahmp.xml
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Since NoahMP precipitation rate calculation was moved to GFS_MP_generic_post_run, sfc_noahmp_pre is no longer needed, so it is deleted from the CCPP configuration file and SDFs. Also, precipitation rate variables used in RUC LSM and NoahMP LSM are put in the Sfcprop DDT rather than the catch-all TBD DDT.
> Fix noahmp precip rates

- scm/etc/scripts/gmtb_scm_analysis.py
Hera uses an older version of the Pandas package where the following line causes an error:
`pandas.plotting.register_matplotlib_converters()`
This line was added because not having it there with newer versions of Pandas leads to a "Future Warning". This was put in a try block.
Also, it appears that Hera doesn't have dvipng installed, which is needed to render LaTeX in plots and save as a PNG file. The file format has been changed back to using PDF instead.
Note: This should be merged after the short course since instructions mention PNG, and the AMI has no problem with plotting PNGs.
> Fix Hera plotting

- docker/Dockerfile
remove cmake installation in Dockerfile since base image now has cmake that is new enough for NCEPLIBS; point to tag instead of branch for gmtb-scm
Will need one more update when tag v4.0.0 is actually ready.
> Dockerfile update

- .gitmodules
- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.meta
- scm/src/multi_run_gmtb_scm.py
- scm/src/run_gmtb_scm.py
This PR:
- updates the standard_name entries of several variables following the fix of issue https://github.com/NCAR/ccpp-physics/issues/179 (cleanup radiation tendencies)
- adds Python 3 compatibility for `scm/src/run_gmtb_scm.py` and `scm/src/multi_run_gmtb_scm.py`
- generates a report about successful/failed runs at the end of the multi-run script when the verbose flag is set
- updates the submodule pointers for ccpp/framework and ccpp/physics to include the latest developments
This PR requires https://github.com/NCAR/ccpp-physics/pull/426 to be merged first.
Tested on macOS with
- LLVM clang + GNU gfortran without OpenMP in Debug (DEBUG) mode, using Python 2.7
- GNU gcc+gfortran with OpenMP in PROD (Release) mode, using Python 3.7
> dtc/develop: Python 3 compatibility (run scripts), standard_name updates

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This PR updates the dtc/develop branch with changes required from the recent ccpp-physics changes from EMC, see https://github.com/NCAR/ccpp-physics/pull/434.
This is also an attempt to make the `GFS_typedefs.{F90,meta}` files more consistent between FV3 and SCM to facilitate future comparisons.
This PR can be merged after https://github.com/NCAR/ccpp-physics/pull/434 was merged.
Testing: this code compiles and runs successfully on
- macOS with LLVM clang + GNU gfortran in DEBUG mode
- macOS with GNU gcc + GNU gfortran in PROD mode
> Update NCAR dtc/develop: apply updates from CCN/IN commit

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- update GFS_typedefs.[F90/meta] to work with latest master of ccpp-physics; update ccpp-physics submodule pointer
Associated PRs:
https://github.com/NOAA-EMC/fv3atm/pull/155
https://github.com/NCAR/ccpp-physics/pull/486
> Update master branch to work with ccpp-physics master

- ccpp/physics_namelists/input_GFS_v15p2.nml
- ccpp/physics_namelists/input_GFS_v15p2_ACM.nml
- ccpp/physics_namelists/input_GFS_v15p2_FA.nml
- ccpp/physics_namelists/input_GFS_v15p2_MYJ.nml
- ccpp/physics_namelists/input_GFS_v15p2_RRTMGP.nml
- ccpp/physics_namelists/input_GFS_v15p2_RRTMGP_LWjac.nml
- ccpp/physics_namelists/input_GFS_v15p2_YSU.nml
- ccpp/physics_namelists/input_GFS_v15p2_noahmp.nml
- ccpp/physics_namelists/input_GFS_v15p2_saYSU.nml
- ccpp/physics_namelists/input_GFS_v16beta.nml
- ccpp/physics_namelists/input_GFS_v16beta_RRTMGP.nml
- ccpp/physics_namelists/input_GFS_v16beta_RRTMGP_LWjac.nml
- ccpp/physics_namelists/input_GSD_v1.nml
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
update GFS_typedefs.[F90/meta] and ccpp/physics_namelists (to remove do_sfcperts) to work with latest ccpp-physics master
> update SCM to work with ccpp-physics master (8/31/2020)

- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.meta
- scm/src/gmtb_scm_kinds.meta
- scm/src/gmtb_scm_physical_constants.meta
- scm/src/gmtb_scm_type_defs.meta
This PR follows https://github.com/NOAA-EMC/fv3atm/pull/153 in order to work with dependencies in the CCPP metadata and "active" attribute in the same.
Associated PRs:
https://github.com/NCAR/ccpp-framework/pull/317
https://github.com/NCAR/ccpp-physics/pull/483
This compiles/runs on Mac/GNU. Have not tested on other platforms.
> update SCM for adding CCPP dependencies to metadata and active attribute

- ccpp/physics_namelists/input_GFS_v15p2.nml
- ccpp/physics_namelists/input_GFS_v15p2_ACM.nml
- ccpp/physics_namelists/input_GFS_v15p2_FA.nml
- ccpp/physics_namelists/input_GFS_v15p2_MYJ.nml
- ccpp/physics_namelists/input_GFS_v15p2_RRTMGP.nml
- ccpp/physics_namelists/input_GFS_v15p2_RRTMGP_LWjac.nml
- ccpp/physics_namelists/input_GFS_v15p2_YSU.nml
- ccpp/physics_namelists/input_GFS_v15p2_noahmp.nml
- ccpp/physics_namelists/input_GFS_v15p2_saYSU.nml
- ccpp/physics_namelists/input_GFS_v16beta.nml
- ccpp/physics_namelists/input_GFS_v16beta_RRTMGP.nml
- ccpp/physics_namelists/input_GFS_v16beta_RRTMGP_LWjac.nml
- ccpp/physics_namelists/input_GSD_v1.nml
- ccpp/physics_namelists/input_csawmg.nml
This PR builds on https://github.com/NCAR/gmtb-scm/pull/213 (should be merged afterward).
It only updates SCM suites to function like FV3-based ones. No changes in SDFs were detected, but several changes in namelist settings were. They include:
- add qdiag3d = T for all suites (SCM-only change, since we always want to output moisture tendencies)
- add effr_in = T for the GSD_v1 suite
- set iccn = 1 in CSAWMG suite
> Update SCM suites to match FV3

- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- add changes to ccpp_prebuild.py, GFS_typedefs.F90/meta following changes to RRTMGP
- these changes follow https://github.com/NOAA-EMC/fv3atm/pull/208
> Hotfix to fix ccpp_prebuild errors following RRTMGP changes

- scm/src/run_gmtb_scm.py
This PR fixes a logic error in the run script related to switching to prescribed_surface SDF when using the old input format. The bug reset the surface_flux_spec variable to False when using existing prescribed surface cases, even after it had been set to True from the case configuration file. This caused existing prescribed surface cases to try to use an active LSM without being properly initialized, resulting in a seg fault.
Thanks @egrell for reporting the problem.
> Run script bugfix

- scm/src/gmtb_scm_input.F90
This PR fixes another bug reported by @egrell where the kinematic surface fluxes from existing specified surface flux cases were being read into a variable that holds surface fluxes in W m-2. This caused the surface fluxes used in the case to be set to their initial values (0) rather than those read from file.
This should hopefully be the last bugfix for existing specified surface flux cases introduced during the development to support the DEPHY format since I ran the same case using code before the DEPHY changes and, as of this PR, the output was identical.
> Another specified surface flux input bugfix

- scm/src/CMakeLists.txt
- scm/src/cmake/modules/FindNetCDF.cmake
- make the switch to new NCEPLIBS-external/NCEPLIBS generic, not just for hera.intel
- use correct linker flags for new NCEPLIBS-external/NCEPLIBS
- bump up cmake to fix annoying cmake 0048 policy warnings
> release/v5: build system updates and bug fixes

- contrib/build_nceplibs.sh
Minor build_nceplibs.sh change. This was suggested by @gthompsnWRF.
> change build_nceplibs.sh to handle relative nceplibs dir path

- .pylintrc
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/gmtb_scm_qsub_example.py
- Update version of GNU compiler from 8.3.0 to 9.1.0 to compile ccpp-…physics (b127d9b)
- Add gmtb_scm_qsub_example.py for batch jobs on Cheyenne
- Add .pylintrc file
Tests run on Cheyenne:
- gmtb_scm_qsub_example.py: pylint rated at 10.00/10
- GNU build successful
- Running multi_run_gmtb_scm.py succeeds using gmtb_scm_qsub_example.py script and GNU build testing all supported suites and cases
- Intel build successful
- Running multi_run_gmtb_scm.py succeeds using gmtb_scm_qsub_example.py script and Intel build testing all supported suites and cases
> Initial commit for regression testing of CCPP SCM

- scm/src/gmtb_scm_type_defs.F90
Problem: For cases in the DEPHY format, the roughness length was not being properly initialized from the data file. It was read in properly, but in the case where the case data file does not contain model or LSM initial conditions, the values of the fractional landmask roughness length values (zorll, zorli, zorlw) were not being set from the one that is read in (zorlo). The logic assumed that input_zorl[l,i,w] would be set to a missing value (negative), but that does not happen in the read routine for the DEPHY format.
Solution: Modify the logic to set zorl[l,i,w] from zorlo if the input values are negative (missing) or zero (set to their initialization values).
Fixes #228
> Fix zero roughness length using DEPHY format with non-LSM ICs

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm.F90
- scm/src/scm_input.F90
- scm/src/scm_setup.F90
- scm/src/scm_type_defs.F90
This updates the main branch of the SCM to work with the main branch of ccpp-physics as of 1 July, 2021.
This superficially follows https://github.com/NOAA-EMC/fv3atm/pull/310. That is, the changes to GFS_typedefs.F90/meta are brought over and the new tracer_types array now exists, but is set to all zeros. If GOCART is ever to be used with the SCM in the future, more of the fv3atm PR will probably need to be brought over and the tracer files reworked to support the different chemistry classifications.
> update GFS_typedefs.F90/meta to work with latest main ccpp-physics

- scm/src/multi_run_scm.py
- test/rt.sh
- test/summarize.sh
- Add ``--timer`` option to call to ``multi_run_scm.py`` in ``rt.sh``.  The execution time includes file
operations performed by the single run script in addition to the execution of the SCM executable.
By default, this option will execute one integration of each subprocess.
- Modify ``spawn_process`` in ``multi_run_scm.py`` to return ``elapsed_time`` and do the ``logging.info()``
call in the main subroutine to allow output of case and suite name with elapsed time
- Add grep for elapsed time in output file
All tests pass on Cheyenne, Hera and MacOS.
Sample output from Cheyenne, Intel Release, 3 day run time:
Timing Information:
===================
INFO: elapsed time: 29.44097218999741 s for case: arm_sgp_summer_1997_A suite: SCM_GFS_v15p2
INFO: elapsed time: 29.78753030200096 s for case: …
> Feature/add timing  Add release branch timing information to SCM regression test output.

- CODEOWNERS
- scm/etc/scripts/plot_configs/all_vars_test_twpice.ini
- scm/etc/scripts/scm_analysis.py
- scm/src/scm.F90
- scm/src/scm_output.F90
- scm/src/scm_utils.F90
- move increment of itt_out to output_append to be consistent with other output time indices
- add option to force writing instantaneous output (outside of normal cadence, e.g. initial conditions)
- call output_append at every timestep and return if no output should be written during current timestep
- fix bug when n_rad == 1 and/or when radiation is not called (missing value fills)
- fix type of initial date variables (thanks @MicroTed))
- write out appropriate missing value depending on output datatype in NetCDF_def_var (thanks @MicroTed)
This should cause failed SCM RTs due to changed output files.
> Fix output-related bugs

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This pull request catches the SCM up to the latest ccpp-physics main as of Jan 25, 2022 and implements changes to be consistent with the fv3atm pull requests listed below.
**Associated PRs:**
ccpp-physics
- https://github.com/NCAR/ccpp-physics/pull/806
- https://github.com/NCAR/ccpp-physics/pull/808
- https://github.com/NCAR/ccpp-physics/pull/809
- https://github.com/NCAR/ccpp-physics/pull/812
- https://github.com/NCAR/ccpp-physics/pull/816
- https://github.com/NCAR/ccpp-physics/pull/817
- https://github.com/NCAR/ccpp-physics/pull/818
- https://github.com/NCAR/ccpp-physics/pull/819
- https://github.com/NCAR/ccpp-physics/pull/821
- https://github.com/NCAR/ccpp-physics/pull/822
- https://github.com/NCAR/ccpp-physics/pull/823
- https://github.com/NCAR/ccpp-physics/pull/824
ccpp-framework
- …
> Update SCM to the latest ccpp-physics/framework main

- scm/etc/Hera_setup_intel.csh
- scm/etc/Hera_setup_intel.sh
Fixes https://github.com/NCAR/ccpp-scm/issues/298
Hera sysadmins changed how python is managed on Hera: https://rdhpcs-common-docs.rdhpcs.noaa.gov/wiki/index.php/Anaconda#Migrating_from_the_old_.22RDHPCS_mirror.22_installation_to_the_Anaconda_installation
Specifically, installing shapely, configobj, and netCDF4 using the method of grabbing the modules from the RDHPCS mirror does not work any more. According to their documentation, the preferred method for managing python is for users to install their own version of Miniconda and use that, which is what I did on Hera.
- I installed miniconda in /scratch1/BMC/gmtb/SCM_anaconda on Hera 
- create new "pyccpp" environment to maintain for CCPP SCM users (we can install whatever packages that we want in that environment in the future); this …
> update Hera setup scripts

- docker/Dockerfile
- scm/src/run_scm.py
- Updating Dockerfile for latest release
- Adding myself as a maintainer
- restoring the old NCEPLIBS build script as a stopgap before we upgrade to newest hpc-stack or spack
- Call new data retrieval script
- Add environment variables that are needed for running so user doesn't need to set them manually
- Updating run script
- Remove extra debug layer to avoid having normal messages show up as warnings
- Update "copy_outdir" function to be able to work from any directory, not just run directory (this prevents errors in docker container)
Tests run: Used this branch (modified slightly to avoid chicken-egg problem) to build dockerfile and run tutorial case successfully with resulting docker image (can be downloaded from Dockerhub: `docker pull dtcenter/ccpp-scm:v6.0.0-beta`)
> Some Tutorial and Docker-related updates for v6

- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
This conda environment was created using the following commands, and was sufficient to run the online tutorial case:
```
conda create --prefix=/glade/p/ral/jntp/GMTB/CCPP_SCM/conda/ccpp-scm python=3.7
conda activate /glade/p/ral/jntp/GMTB/CCPP_SCM/conda/ccpp-scm/
conda install -c conda-forge xarray dask netCDF4 bottleneck matplotlib f90nml xesmf
conda install configobj
```
It has been tested successfully with the online tutorial case for Intel with bash shell, I have not tested other configurations yet.
> Add new conda environment to Cheyenne setup files

- scm/etc/Cheyenne_setup_gnu.sh
The Cheyenne GNU environment setup file had some extra spaces in variable assignments, causing errors. This fixes that issue.
> Fix environment variable declarations for Cheyenne GNU bash

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This PR updates GFS_typedefs.[F90/meta] in order to work with PR#2 of the ufs/dev fork and https://github.com/NCAR/ccpp-physics/pull/971 of the NCAR/main fork.
> ufs/dev PR#2

- scm/etc/Cheyenne_setup_gnu.csh
- scm/etc/Cheyenne_setup_gnu.sh
- scm/etc/Cheyenne_setup_intel.csh
- scm/etc/Cheyenne_setup_intel.sh
- scm/etc/Hera_setup_intel.csh
- scm/etc/Hera_setup_intel.sh
See https://github.com/ufs-community/ufs-weather-model/issues/1465 for info on using EPIC's latest hpc-stack on Hera and Cheyenne.
> hpc-stack update (critical for using Hera)

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- update GFS_typedefs.F90/meta to have latest changes for external land component support
> Updates for ccpp-physics ufs-dev PR#10

- scm/src/CCPP_typedefs.F90
- scm/src/CCPP_typedefs.meta
- only new changes should be ccpp/physics submodule pointer and edits to CCPP_typedefs.F90/meta
- contains changes from #351 (that will be merged first)
> Updates for ccpp-physics ufs-dev PR#14

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This updates GFS_typedefs to work with the latest ccpp/physics on the NCAR fork, main branch.
Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/992
https://github.com/NCAR/fv3atm/pull/79
https://github.com/NCAR/ufs-weather-model/pull/81
> UFS-dev PR#27

- ccpp/config/ccpp_prebuild_config.py
- ccpp/suites/suite_SCM_GFS_v15p2_RRTMGP.xml
- ccpp/suites/suite_SCM_GFS_v15p2_RRTMGP_ps.xml
- ccpp/suites/suite_SCM_GFS_v16_RRTMGP.xml
- ccpp/suites/suite_SCM_GFS_v16_RRTMGP_ps.xml
- scm/src/CCPP_typedefs.F90
- scm/src/CCPP_typedefs.meta
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
update typedefs, SDFs, submodule pointers, and ccpp_prebuild_config.py to work with ccpp-physics ufs-dev/PR#34
> UFS/dev PR#34 (RRTMGP refactoring)

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to GFS_typedefs that are identical to https://github.com/NCAR/fv3atm/pull/88.
Depends on https://github.com/NCAR/ccpp-physics/pull/1006 being merged first.
> UFS-dev PR#53

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to GFS_typedefs to work with [ufs/dev #42](https://github.com/NCAR/ccpp-physics/pull/1007). The changes are analogous to https://github.com/NCAR/fv3atm/pull/89
> UFS-dev PR#42

- .gitmodules
- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Updates to GFS_typedefs and ccpp_prebuild_config.py to work with https://github.com/NCAR/ccpp-physics/pull/1008. This has changes analogous to https://github.com/NCAR/fv3atm/pull/90.
Note that additional changes for input might be needed to use the smoke/dust code.
> UFS/dev PR#54

- .gitmodules
- ccpp/config/ccpp_prebuild_config.py
- ccpp/suites/suite_SCM_HRRR.xml
- scm/src/CCPP_typedefs.F90
- scm/src/CCPP_typedefs.meta
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm_physical_constants.F90
- scm/src/scm_physical_constants.meta
analogous to https://github.com/NOAA-EMC/fv3atm/pull/606
Note that although these changes allow the SCM to compile and run through the field campaign cases, more work will need to be done in the input and UFS column simulator script to work with a lake point.
> UFS-dev PR#26

- .gitmodules
Hotfix for .gitmodules accidentally not pointing to NCAR/main.
> update .gitmodules to point to main

- .github/workflows/ci_build_scm_ubuntu_22.04.yml
- .github/workflows/ci_run_scm_DEPHY.yml
- .github/workflows/ci_run_scm_rts.yml
DESCRIPTION OF CHANGES: Using h5py>=3.4 to avoid 'H5Pset_fapl_ros3 is undefined' error within Conda's Python NetCDF installation.
TESTS CONDUCTED: Passes ci_run_scm_rts 
NOTES: ~If this versioning issue effects the other GitHub action workflows, I'll edit this PR to fix the others.~ It did effect other workflows, copied the changes to those files as well.
> Workflow ci_run_scm_rts Versioning Bugfix

- .gitmodules
Only update to ccpp/physics submodule necessary (no changes to typedefs).
includes changes from #402 until it is merged.
> UFS-dev PR#69

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NCAR/fv3atm/pull/105
> UFS-dev PR#98

- .gitmodules
- scm/src/CCPP_typedefs.F90
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NCAR/fv3atm/pull/125
> UFS-dev PR#110

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NCAR/fv3atm/pull/114
> UFS-dev PR#122

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to work with https://github.com/NCAR/ccpp-physics/pull/1057
> UFS-dev PR#135

- .gitmodules
- ccpp/config/ccpp_prebuild_config.py
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Changes to work with https://github.com/NCAR/ccpp-physics/pull/1058
> UFS-dev PR#94

- .github/workflows/ci_run_scm_rts.yml
- ccpp/physics_namelists/input_GFS_v16.nml
- test/cmp_rt2bl.py
- test/cmp_scmout.py
- test/plot_scm_out.py
This PR contains the following changes:
- Update to SCM RT Baseline (Thanks @mkavulich)
- More cleanup of the plotting script.
- New comparison script for offline use (uses the same plotting script as in the RT CI)
> Updates to CI and plotting

- scm/src/CMakeLists.txt
The fix 
- finds the MPI package and requires `mpi_f08` module. 
- include the MPI module paths, this fixes the following `use mpi_f08` error in `framework/src/ccpp_types.F90`
Current Error:
```
$ make
[  0%] Building Fortran object ccpp/framework/src/CMakeFiles/ccpp_framework.dir/ccpp_types.F90.o
/glade/work/soren/src/ccpp/upstream/scm-upstream/ccpp/framework/src/ccpp_types.F90:22:9:
22 |     use mpi_f08, only: MPI_Comm
|         1
Fatal Error: Cannot open module file 'mpi_f08.mod' for reading at (1): No such file or directory
compilation terminated.
```
> bugfix: CMake build missing mpi_f08 module paths

- .github/workflows/ci_build_scm_ubuntu_22.04_nvidia.yml
Fixing Github runner nvidia MPI installation and caching. List of changes
- installing OpenMPI v4.1.6 manually, making MPI compilers default
- installing curl and zlibs with apt-get instead of manually
- bumping actions' versions
- quiet wget and tarball expansion
- small changes to caching and `PATH` and `LD_LIBRARY_PATH` variable setting. Separated from build steps
NOTE: nvidia-with-GPU build still fails
> bugfix: NVidia Github Actions

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm_output.F90
Updates to work with https://github.com/NOAA-EMC/fv3atm/pull/836
Also contains changes from:
https://github.com/NOAA-EMC/fv3atm/pull/835
> UFS-dev PR#207

- scm/doc/TechGuide/chap_cases.rst
- scm/etc/scm_qsub_example.py
- scm/etc/scripts/GABLS3_LSM.ncl
- scm/etc/scripts/GABLS3_LSM_NoahMP.ncl
- scm/etc/scripts/GABLS3_LSM_RUC.ncl
- test/README.md
- test/rt.sh
Updating scripts and documentation to reflect NCAR's move from Cheyenne to Derecho clusters. Need to find the paths to UFS_RTs on Derecho and then the PR will be moved from `draft` to `ready for review`.
``` Bash
scm/etc/scripts/GABLS3_LSM.ncl:;  gl_dir = "/glade/scratch/damico/GLDAS_GABLS3/"
scm/etc/scripts/GABLS3_LSM_RUC.ncl:;  gl_dir = "/glade/scratch/damico/GLDAS_GABLS3/"
scm/etc/scripts/GABLS3_LSM_NoahMP.ncl:;  gl_dir = "/glade/scratch/damico/GLDAS_GABLS3/"
scm/doc/TechGuide/chap_cases.rst:   ./UFS_forcing_ensemble_generator.py -d /glade/scratch/epicufsrt/GMTB/CCPP-SCM/UFS_RTs/control_c192/ -sc --C_RES 192 -dt 360  -n control_c
192 -lons 300 -lats 34
scm/doc/TechGuide/chap_cases.rst:   ./UFS_forcing_ensemble_generator.py -d /glade/scratch/epicufsrt/GMTB/CCPP-SCM/UFS_RTs/control_c384/ …
```
> Cheyenne to Derecho Script and Documentation Update

- .github/workflows/ci_test_docker.yml
- docker/Dockerfile
- scm/src/CCPP_typedefs.F90
- scm/src/GFS_typedefs.F90
- scm/src/run_scm.py
- scm/src/scm.F90
- scm/src/scm_forcing.F90
- scm/src/scm_input.F90
- scm/src/scm_setup.F90
- scm/src/scm_time_integration.F90
- scm/src/scm_utils.F90
- scm/src/scm_vgrid.F90
ISSUE FIXED: Docker Github Actions CI was failing
DESCRIPTION OF CHANGES: 
- Installing OpenMPI and python3-netcdf4 packages to meet MPI and NetCDF requirements. For local development cmake-curses-gui was needed, also added non-GUI Emacs for development.
- Docker prefers apt-get to install packages but f90nml wasn't available for that, needed to use pip with `--break-system-packages`. No need for a virtual environment now.
- Cleaned up Docker warnings by switching to `LABEL` and `ENV foo=bar`
> bugfix: dockerfile build and CI error reporting

- scm/etc/scripts/UFS_case_gen.py
- scm/etc/scripts/UFS_forcing_ensemble_generator.py
Running the case generation on LAM output from UFS SRW does not currently work. These updates fix that.
Sample LAM data can be found on Hera: /scratch1/BMC/gmtb/Tracy.Hertneky/phys_tne/socrates/2018020412
Sample case over the S. Ocean was created with the following command:
./UFS_forcing_ensemble_generator.py -d /scratch1/BMC/gmtb/Tracy.Hertneky/phys_tne/socrates/2018020412 -n socrates -lons 133 -lats -51.5 -dt 75 -cres 768 -sdf SCM_GFS_v16 -sc -lam -fm 2 -vm 2
./run_scm.py --npz_type gfs --file scm_ufsens_socrates.py --timestep 75 -l 64 --n_itt_out 48 --n_itt_diag 48
Comparison of SCM to UFS column:
Diffs could be attributable to diff suite used (HRRR_gf for UFS vs GFS_v16 for SCM, since HRRR_gf was not working from case_gen input)
> update case-gen scripts for LAM capability

- scm/etc/scripts/plot_configs/twpice_all_suites.ini
The tutorial (specifically https://dtcenter.org/ccpp-scm-online-tutorial/exercise-1-run-scm-examine-results) needs these changes to work.
Without this, the plotting script will fail.
> update plot_config file for tutorial

- scm/doc/TechGuide/chap_quick.rst
- scm/etc/scm_qsub_example.py
LIST OF CHANGES
- Adding documentation for `run_scm.py`'s `--mpi_command` argument
- Batch script `scm_qsub_example.py` needed `cd $PBS_O_WORKDIR` added to the command so it would work on Derecho
> v7 release: --mpi_command documentation and scm_qsub_example.py fix

- .github/workflows/ci_scm_ccpp_prebuild.yml
- README.md
- Updating README with v7 documentation and adding build, version, and Zenodo badges. 
- Added short description of SCM with links to CCPP and Framework repos.
- Renaming Github Action so Github Action badge will say "build" instead of "CI test to run SCM ccpp_prebuild scipt".
> README v7 Updates With Build and Zenodo Badges

- README.md
A small single `:` was breaking the CCPP Framework link in the README. This should be a quick one to review. 😉
> bugfix: broken CCPP Framework link fix

- .github/workflows/ci_run_scm_rts.yml
- .gitmodules
- ccpp/config/ccpp_prebuild_config.py
- ccpp/suites/suite_SCM_GFS_v16_debug.xml
- ccpp/suites/suite_SCM_GFS_v16_debug_ps.xml
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm.F90
- scm/src/scm_output.F90
- scm/src/scm_setup.F90
- scm/src/scm_type_defs.F90
- scm/src/scm_type_defs.meta
- scm/src/suite_info.py
- test/rt_test_cases.py
Changes similar to https://github.com/NOAA-EMC/fv3atm/pull/798
Additional changes:
- Make the interstitial DDT in the SCM physics DDT an array of (n_threads) size so that GFS_Debug can work (this is how UFS does it)
-- downstream changes for the above change
RT notes: This PR doesn't change RT results except for the addition of a new test that exercise the GFS_debug.F90 schemes. Note that the `GFS_abort` scheme in GFS_debug.F90 is untested because it causes a run failure (on purpose) and CI flags it as a failure, which we don't necessarily want.
> UFS-dev PR#183

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
Analogous to https://github.com/NOAA-EMC/fv3atm/pull/861 and https://github.com/NOAA-EMC/fv3atm/pull/815
Note that fire coupling is not used/tested with the SCM, so changes from https://github.com/NOAA-EMC/fv3atm/pull/815 are mainly superficial.
No regression test changes.
> UFS-dev PR#220

- contrib/get_aerosol_climo.sh
- contrib/get_all_static_data.sh
- contrib/get_mg_inccn_data.sh
- contrib/get_thompson_tables.sh
The Github Actions logs are being filled up with output from the `wget` download status bar.
Added ability to turn on verbose wget output. Wget output defaults to `-nv` so that the Github Actions output won't be filled with the wget download status. This will make debugging failed testcases easier.
Since I was adding command line arguments I also added `--help` option. 
Some of the script have `set -ex` and some have it commented out. Should we default to the same behavior for all the scripts?
Tested scripts by hand.
> Contrib data script's wget verbosity

- contrib/get_aerosol_climo.sh
- contrib/get_all_static_data.sh
- contrib/get_mg_inccn_data.sh
- contrib/get_thompson_tables.sh
DESCRIPTION OF CHANGES: CI after PR #526 is still producing too much output. This must be a Github CI only thing since I can't replicate the behavior locally. Switching the default to `-q` (no output) from `-nv` for `wget` to see if that fixes things.
CI OUTPUT:
> Contrib data script's wget verbosity fix

- scm/src/scm_input.F90
- scm/src/scm_setup.F90
1. Correctly assign area from the DEPHY forcing file. -> pulled out of the "if surfaceForcingLSM = lsm" statement since some canned cases have "surface_forcing_lsm = none".
2. Allow column_area to override scm_state%area if it is defined in the case_confil nml. When not defined in the case_config, scm_state%area is zero. In this case, use the default case area from the DEPHY forcing file.
@grantfirl @dustinswales Should there also be logic if area is not present in DEPHY file and not in the nml? (probably) Should there be some logging added to write what area is being used? LMK and I can add.
#540
> Fix area logic in SCM

- scm/doc/TechGuide/chap_ccpp.rst
Support forum link was pointing to old url that doesn't exist anymore.
This PR will complete the final task in Issue #422
> Docs: Updating link to support forum

- ccpp/config/ccpp_prebuild_config.py
- ccpp/physics_namelists/input_HRRR_gf.nml
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm_physical_constants.F90
- scm/src/scm_physical_constants.meta
This PR catches the NCAR:main branch of the SCM up with changes from the ufs-community:ufs/dev ccpp-physics branch since Thanksgiving 2024. All changes have previously been reviewed via PRs into ufs-community:ufs/dev and previously tested using UFS RTs. This PR (together with https://github.com/NCAR/ccpp-physics/pull/1109) has been regression tested using SCM RTs one PR at-a-time. The results for the regression tests run here should be such that the failed tests correspond to the superset of tests listed in the comments for individual PRs.
Associated fv3atm PRs:
- https://github.com/NOAA-EMC/fv3atm/pull/866 (no baseline change)
- https://github.com/NOAA-EMC/fv3atm/pull/882 (baseline changes tests using Thompson MP - see comment below)
- https://github.com/NOAA-EMC/fv3atm/pull/883 …
> ufs/dev "omnibus" changes from 11/2024-02/2025

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
This PR catches the NCAR:main with changes from the ufs-community:ufs/dev branch. 
- ufs-community/ccpp-physics#235
- NOAA-EMC/fv3atm#896
- NCAR/ccpp-physics#1111
NOTE: I forgot to turn off the automatic whitespace cleanup, if this is an issue I can add those back in!
> UFS-dev PR#235

- scm/src/GFS_typedefs.F90
- scm/src/scm_forcing.F90
- scm/src/scm_input.F90
- scm/src/scm_vgrid.F90
Reducing GNU `-Wall` warnings per issue [#495](https://github.com/NCAR/ccpp-physics/issues/495).
Commits solve the following warning flags implied in `-Wall`
| Compiler Flag                | Description                                                                                             |
| ----------------------- | -------------------------------------------------------------------- | 
| -Wampersand                | Warn about missing ampersand in continued character constants      |
| -Wtabs                           | By default, tabs are accepted as whitespace, but tabs are not members of the Fortran Character Set.  |
> GNU -Wall Warning Reduction: ampersand and tabs

- ccpp/suites/suite_SCM_GFS_v17_p8_ugwpv1_no_nsst.xml
- ccpp/suites/suite_SCM_GFS_v17_p8_ugwpv1_no_nsst_ps.xml
- ccpp/suites/suite_SCM_RRFS_v1beta_no_nsst.xml
- ccpp/suites/suite_SCM_RRFS_v1beta_no_nsst_ps.xml
- scm/doc/TechGuide/chap_cases.rst
- scm/etc/case_config/atomic_Feb02T21Feb04T05.nml
- scm/etc/case_config/atomic_Feb08T12Feb09T20.nml
- scm/etc/case_config/atomic_Feb09T12Feb10T20.nml
- scm/etc/case_config/atomic_Jan16T22Jan18T06.nml
- scm/etc/case_config/atomic_Jan18T21Jan20T05.nml
- scm/etc/case_config/atomic_Jan22T21Jan24T05.nml
- scm/etc/case_config/atomic_Jan30T23Feb01T07.nml
- scm/src/suite_info.py
- test/rt_test_cases.py
This pull request introduces forcing and namelists associated with the ATOMIC field campaign. Specifically:
- **Adding DEPHY-format associated case configuration namelist files, which will be named as atomic_[period].nml, into scm/etc/case_config/.** There are seven periods in total.
- **Adding suite_SCM_GFS_v17_p8_ugwpv1_no_nsst.xml and suite_SCM_RRFS_v1beta_no_nsst.xml into ccpp/suites/.** This change allows the ATOMIC test case to be run using the 'sfc_ocean' scheme (instead of 'nsst'), which may work more properly for the oceanic field campaign cases (as suggested by [Issue #518](https://github.com/NCAR/ccpp-scm/issues/518)).  
- **Modifying suite_info.py in scm/src/ and rt_test_cases.py in test/ accordingly.** These changes enable the CCPP SCM to run the SCM_GFS_v16_no_nsst, …
> Introducing ATOMIC test case

- scm/etc/modules/hera_gnu_spack_stack_1.9.1.lua
- scm/etc/modules/hera_intel_spack_stack_1.9.0.lua
- scm/etc/modules/hera_intel_spack_stack_1.9.1.lua
I created a new modulefile to use an experimental installation of spack-stack 1.9.0 from Ratko Vasic on Hera.
To use:
- cd to the top level of ccpp-scm
- module use scm/etc/modules
- module load hera_intel_spack_stack_1.9.0
This load the spack-stack installation of python, although following https://spack-stack.readthedocs.io/en/1.6.0/MaintainersSection.html, I've created a new virtual environment using the spack-stack 1.9.0 python that should have every python package needed by any and all python scripts in the CCPP SCM repo. The environment is located in /scratch1/BMC/gmtb/ccpp-scm-software/spack-stack-1.9.0. To activate this virtual environment:
- source /scratch1/BMC/gmtb/ccpp-scm-software/spack-stack-1.9.0/bin/activate
> Try spack-stack 1.9.0 on Hera for unifying python environment

- scm/src/CCPP_typedefs.F90
- scm/src/CCPP_typedefs.meta
Changes combined from PRs 232 and 256
Associated fv3atm PRs:
NOAA-EMC/fv3atm [#993](https://github.com/NOAA-EMC/fv3atm/pull/933)
NOAA-EMC/fv3atm [#885](https://github.com/NOAA-EMC/fv3atm/pull/885)
> UFS dev PR#232/256

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm_type_defs.F90
- test/cmp_scmout.py
Original description/work from @dustinswales:
This PR moves the GFDL_parse_tracers file from the physics to the host (where it belongs)
Also, is a small bugfix in a plotting script.
@grantfirl update:
- remove parse_tracers module entirely since we can use a local version of get_tracer_index() already in SCM code
- move get_tracer_index() function from scm_type_defs to GFS_typedefs to avoid circular dependency
> Updated version of "Move parse_tracers file from physics to host"

- .github/workflows/ci_build_scm_ubuntu.yml
- .github/workflows/ci_build_scm_ubuntu_nvidia.yml
- .github/workflows/ci_run_scm_DEPHY.yml
- .github/workflows/ci_run_scm_rts.yml
- .github/workflows/ci_run_scm_ufs_replay.yml
- .github/workflows/ci_scm_ccpp_prebuild.yml
- .github/workflows/ci_test_docker.yml
Changes to fix warnings from Github CI runs. 
- Change all to latest Ubuntu runner option, 20.04 is being deprecated.
- Simplifying test names and renaming files for move to latest Ubuntu runner
- Testing with Spack Python versions 3.11.7 and latest
- Updating NVIDIA HPC SDK release, only building and not using Conda to reduce space
- Adding more unique cache names
- Fixes warning if plots aren't created
- ftp site was taken down, moving location of replay
> warning fixes: Github Actions Updates

- ccpp/physics_namelists/input_GFS_v17_p8_ugwpv1.nml
- scm/etc/tracer_config/tracers_GFS_v17_p8_ugwpv1.txt
- scm/src/CCPP_typedefs.F90
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- scm/src/scm_output.F90
- scm/src/scm_type_defs.F90
- ufs-community/ccpp-physics[#246](https://github.com/ufs-community/ccpp-physics/pull/246)
- NOAA-EMC/fv3atm[#914](https://github.com/NOAA-EMC/fv3atm/commit/b1b3454787e99ba57346a6b35a5cec6ef09fbace#diff-556dd5101e3670a87a153795ecfc199359bd8d3da8b1fa84aeb6596a88d61ea2)
- NCAR/ccpp-physics[#1121](https://github.com/NCAR/ccpp-physics/pull/1121)
---
REGRESSION TEST CHANGES:
Expected changes from UWM tests:
cpld_control_p8_faster intel
control_p8_faster intel
hafs_regional_storm_following_1nest_atm_ocn_wav intel
hafs_regional_storm_following_1nest_atm_ocn_wav_inline intel
> Ufs/dev PR#246

- ccpp/physics_namelists/input_GFS_v17_p8_ugwpv1.nml
- ccpp/physics_namelists/input_GFS_v17_p8_ugwpv1_ps.nml
- ccpp/physics_namelists/input_RAP.nml
- scm/etc/case_config/DYNAMO_NSA3a.nml
- scm/src/scm_forcing.F90
- scm/src/scm_input.F90
- scm/src/scm_type_defs.F90
Following discussion with @hertneky, this changes the following:
- Change the initial value of the ocean mixed layer depth (`xz`) to 20.0 m to match UFS
- Change `ifd` or the flag to turn on NSST to 1.0 if the surface is ocean; this only has an effect if prescribed surface fluxes are off and NSST is in the SDF and nstf_name(1) > 0.
-- if `ifd` starts as zero, NSST code can eventually set it to 1 if the model time is after 6 AM local time and ifd starts as 0, but during some cases, it was noticed that `ifd` wouldn't change to 1 (and therefore activate NSST) until the first "sunrise" after the model initializes (e.g. if a case started at noon, `ifd` wouldn't set itself to 1 until the next morning, even though NSST should be active immediately)
- Set the nstf_name(2) value to 1 (NSST …
> NSST initialization changes

- .github/workflows/ci_build_scm_ubuntu_nvidia.yml
- .github/workflows/ci_test_docker.yml
- docker/Dockerfile
DESCRIPTION OF CHANGES: The `build_test_and_push_docker` Github CI always fails for an unknown reason on the `main` branch, turning this check off. The other changes are attempt to reduce the amount of time spent during the Docker image build and reduce the information produced.  Changes are:
- Turn off `build_test_and_push_docker` Github CI for merge of PR into `main` branch
- Unifying apt-get install into one command (modern coding practice)
- using slim debian docker image
- git clones of depth=1 so less data is downloaded
- download test datasets only if running in the PR CI
- `build_test_and_push_docker` Github CI runs 3 minutes faster
TESTS CONDUCTED: Built docker image locally
> bugfix: Github CI and Dockerfile

- .gitmodules
- scm/src/GFS_typedefs.F90
This PR puts the NCAR:main branch one PR behind the ufs-community:ufs/dev branch.
- ufs-community/ccpp-physics#260
- NOAA-EMC/fv3atm#937
- NCAR/ccpp-physics#1133
> ufs-community ccpp-physics PR260 memcheck fixes

- .gitmodules
NOTE: built on top of NCAR/ccpp-physics#1133 and NCAR/ccpp-scm#581 branches. 
- ufs-community/ccpp-physics#259
- NOAA-EMC/fv3atm#940
Associated NCAR Framework PR:
- NCAR/ccpp-framework#653
- NCAR/ccpp-physics#1134
> ufs-dev PR#259 CMake changes

- .github/workflows/build_and_push_docker_latest.yml
- .github/workflows/ci_scm_ccpp_prebuild.yml
ISSUE: It seems that due to changes to NCAR policy, users will [get charged](https://github.com/settings/billing) for Github Actions run on their forked branch. This makes sure this doesn't happen.
- Only run Github Actions CI on upstream `NCAR/ccpp-scm` so users don't get charged for runner time
> Run Github Actions Only On NCAR/ccpp-scm

- .gitmodules
SOURCE: @grantfirl
- updates SCM to work with https://github.com/ufs-community/ccpp-physics/pull/278 and https://github.com/ufs-community/ccpp-physics/pull/285 (no effect on SCM since only updates to gcycle, which the SCM doesn't use)
ISSUE: N/A
ASSOCIATED PRs:
https://github.com/NCAR/ccpp-physics/pull/1144
TESTS CONDUCTED: SCM RTs
https://github.com/ufs-community/ufs-weather-model/pull/2723
https://github.com/NOAA-EMC/fv3atm/pull/960
https://github.com/NCAR/ccpp-physics/pull/1144
https://github.com/ufs-community/ccpp-physics/pull/278
https://github.com/ufs-community/ccpp-physics/pull/285
---
REGRESSION TEST …
> UFS-dev PR#278

- scm/doc/TechGuide/chap_quick.rst
- scm/etc/modules/ursa_gnu_spack_stack_1.9.1.lua
- scm/etc/modules/ursa_intel_spack_stack_1.9.1.lua
SOURCE: Grant
- Added modulefiles for Ursa
- Set up new python virtual environment in /scratch3/BMC/gmtb/ccpp-scm-software/spack-stack-1.9.1 (activated via normal module load)
ISSUE: 
ASSOCIATED PRs: None
TESTS CONDUCTED: Both modulefiles loaded on Ursa. Built, ran, and started analysis script.
REGRESSION TEST CHANGES: None
> Add Ursa support

- docker/Dockerfile
- added 'exec sh' to the entrypoint command of the Dockerfile so the container doesn't exit after starting. Cherry-picked the commit hash `6b561aa5c7d2f719aecb52c70275ce2a190ee8a8` from branch [release/public-v7](https://github.com/NCAR/ccpp-scm/tree/release/public-v7). Added that commit to get the Dockerfile working for the new upcoming v7.0.1 release and to push the new release to Dockerhub
> Dockerfile Entrypoint Fix

- .github/workflows/ci_build_scm_ubuntu_nvidia.yml
- Installing Nvidia nvhpc first and using an older version (25.1), since it is too big otherwise and the runner runs out of space during extraction of the Nvidia tarball. The new Nvidia 25.3 tarball is 1.5GB bigger than the old one
> Nvidia CI Fix

- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- ufs-community/ccpp-physics#279
Associated ufs-wm PR:
- ufs-community/ufs-weather-model#2734
- NOAA-EMC/fv3atm#963
- NCAR/ccpp-physics#1148
> ufs-dev PR279

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
SOURCE: Dustin Swales NOAA-GSL
SCM changes identical to FV3UFS [NOAA-EMC/fv3atm #950](https://github.com/NOAA-EMC/fv3atm/pull/950). 
ISSUE:
N/A
ASSOCIATED PRs:
- NCAR/ccpp-physics [#1149 ](https://github.com/NCAR/ccpp-physics/pull/1149)
> ufs/dev PR295

- .gitmodules
- bugfix: initialize data so it is never NaN. Fixes bug in CI when running the `arm_sgp_summer_1997_A` case and `SCM_WoFS_v0` suite. See Issue NCAR/ccpp-physics#1155 for details
ISSUE: NCAR/ccpp-physics#1155
ASSOCIATED PRs:
-  NCAR/ccpp-physics#1157
TESTS CONDUCTED: CI
> bugfix: CI fix in module_mp_nssl_2mom.F90

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
SOURCE: @grantfirl 
- Changes in GFS_typedefs necessary to run with https://github.com/NCAR/ccpp-physics/pull/1156
ISSUE: None
ASSOCIATED PRs:
https://github.com/NCAR/ccpp-physics/pull/1156
TESTS CONDUCTED: Tested in UFS RTs already. SCM RTs expect some results to change.
https://github.com/ufs-community/ccpp-physics/pull/302
https://github.com/NOAA-EMC/fv3atm/pull/990
https://github.com/NCAR/ccpp-physics/pull/1156
---
REGRESSION TEST CHANGES: Expected saSAS result changes. Also, photochemical diagnostic tendencies will change, so any case with non-zero ozone (all except BOMEX) will change results. BOMEX cases …
> UFS-dev PR#302

- .gitmodules
- scm/src/GFS_typedefs.F90
- scm/src/GFS_typedefs.meta
- ufs-community/ccpp-physics#307
Associated ufsatm PR:
- NOAA-EMC/ufsatm#1001
- NCAR/ccpp-physics#1164
> ufs-community ccpp-physics 307
